import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  getTasks: () => ipcRenderer.invoke('get-tasks'),
  getTask: (id: number) => ipcRenderer.invoke('get-task', id),
  addTask: (name: string, description: string, statusId?: number) => ipcRenderer.invoke('add-task', name, description, statusId),
  deleteTask: (id: number) => ipcRenderer.invoke('delete-task', id),
  updateTask: (id: number, name: string, description: string, statusId?: number) => ipcRenderer.invoke('update-task', id, name, description, statusId),
  getActiveTimer: () => ipcRenderer.invoke('get-active-timer'),
  startTimer: (taskId: number) => ipcRenderer.invoke('start-timer', taskId),
  stopTimer: (taskId: number) => ipcRenderer.invoke('stop-timer', taskId),
  getAllTimeEntries: () => ipcRenderer.invoke('get-all-time-entries'),
  getTimeSummary: () => ipcRenderer.invoke('get-time-summary'),
  deleteTimeEntry: (id: number) => ipcRenderer.invoke('delete-time-entry', id),
  showNotification: (title: string, body: string) => ipcRenderer.invoke('show-notification', title, body),
  toggleTodayTask: (id: number) => ipcRenderer.invoke('toggle-today', id),
  getTodayTasks: () => ipcRenderer.invoke('get-today-tasks'),
  clearTodayDate: (id: number) => ipcRenderer.invoke('clear-today-date', id),
  getStatuses: () => ipcRenderer.invoke('get-statuses'),
  addStatus: (name: string, color: string) => ipcRenderer.invoke('add-status', name, color),
  updateStatus: (id: number, name: string, color: string) => ipcRenderer.invoke('update-status', id, name, color),
  deleteStatus: (id: number) => ipcRenderer.invoke('delete-status', id),
  reorderStatuses: (ids: number[]) => ipcRenderer.invoke('reorder-statuses', ids),
  moveTask: (taskId: number, statusId: number) => ipcRenderer.invoke('move-task', taskId, statusId),
  getAutostart: () => ipcRenderer.invoke('get-autostart'),
  setAutostart: (enabled: boolean) => ipcRenderer.invoke('set-autostart', enabled),
})
