name: Release App
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm & Node.js
        uses: pnpm/setup@v2
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dependencies
        run: pnpm build

      - name: Build and Publish Electron App
        run: pnpm exec electron-builder --linux --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
